--------------------------------------------------------
--  Constraints for Table COURIERS
--------------------------------------------------------

  ALTER TABLE "C##WSHOPR"."COURIERS" MODIFY ("COURIER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##WSHOPR"."COURIERS" MODIFY ("COURIER_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##WSHOPR"."COURIERS" MODIFY ("COURIER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "C##WSHOPR"."COURIERS" MODIFY ("COURIER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "C##WSHOPR"."COURIERS" MODIFY ("COURIER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##WSHOPR"."COURIERS" ADD CONSTRAINT "COURIER_PK" PRIMARY KEY ("COURIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "C##WSHOPR"."CUSTOMERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##WSHOPR"."CUSTOMERS" MODIFY ("CUSTOMER_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##WSHOPR"."CUSTOMERS" MODIFY ("CUSTOMER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "C##WSHOPR"."CUSTOMERS" MODIFY ("CUSTOMER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "C##WSHOPR"."CUSTOMERS" MODIFY ("CUSTOMER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##WSHOPR"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "C##WSHOPR"."EMPLOYEES" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCATIONS_IN_WAREHOUSE
--------------------------------------------------------

  ALTER TABLE "C##WSHOPR"."LOCATIONS_IN_WAREHOUSE" ADD CONSTRAINT "LOCATION_PK" PRIMARY KEY ("LOCATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "C##WSHOPR"."ORDERS" ADD CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "C##WSHOPR"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT_DATES
--------------------------------------------------------

  ALTER TABLE "C##WSHOPR"."PRODUCT_DATES" ADD CONSTRAINT "PRODUCT_DATE_PK" PRIMARY KEY ("PRODUCT_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT_IMAGES
--------------------------------------------------------

  ALTER TABLE "C##WSHOPR"."PRODUCT_IMAGES" ADD CONSTRAINT "PRODUCT_IMAGES_PK" PRIMARY KEY ("PRODUCT_IMG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT_STORAGE
--------------------------------------------------------

  ALTER TABLE "C##WSHOPR"."PRODUCT_STORAGE" ADD CONSTRAINT "LOCATION_U" UNIQUE ("LOCATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUPPLIERS
--------------------------------------------------------

  ALTER TABLE "C##WSHOPR"."SUPPLIERS" ADD CONSTRAINT "SUPPLIERS_PK" PRIMARY KEY ("SUPPLIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS"  ENABLE;
