REM INSERTING into C##WSHOPR.EMPLOYEES
SET DEFINE OFF;
Insert into C##WSHOPR.EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME) values (1,'John Smith');
Insert into C##WSHOPR.EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME) values (2,'Smith John');
Insert into C##WSHOPR.EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME) values (3,'Robert Johnson');
Insert into C##WSHOPR.EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME) values (4,'Jenny Smoth');
