REM INSERTING into C##WSHOPR.ORDERS
SET DEFINE OFF;
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (1,1,to_date('02-FEB-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (2,1,to_date('01-FEB-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (3,1,to_date('15-JAN-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (4,3,to_date('12-FEB-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (5,3,to_date('10-FEB-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (6,3,to_date('07-FEB-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (7,3,to_date('06-FEB-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (8,4,to_date('10-FEB-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (9,5,to_date('07-FEB-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (10,5,to_date('09-FEB-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (11,6,to_date('04-FEB-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (12,8,to_date('26-JAN-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (13,9,to_date('28-JAN-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (14,10,to_date('20-JAN-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (15,11,to_date('08-JAN-22','DD-MON-RR'),0,null);
Insert into C##WSHOPR.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_COMPLETED,ORDER_DATE_COMPLETED) values (16,12,to_date('06-FEB-22','DD-MON-RR'),0,null);
