REM INSERTING into C##WSHOPR.PRODUCT_DATES
SET DEFINE OFF;
Insert into C##WSHOPR.PRODUCT_DATES (PRODUCT_ID,PRODUCT_DATE,LOCATION_ID) values (2,to_date('08-JUN-22','DD-MON-RR'),7);
Insert into C##WSHOPR.PRODUCT_DATES (PRODUCT_ID,PRODUCT_DATE,LOCATION_ID) values (13,to_date('03-OCT-22','DD-MON-RR'),6);
Insert into C##WSHOPR.PRODUCT_DATES (PRODUCT_ID,PRODUCT_DATE,LOCATION_ID) values (13,to_date('05-OCT-22','DD-MON-RR'),6);
Insert into C##WSHOPR.PRODUCT_DATES (PRODUCT_ID,PRODUCT_DATE,LOCATION_ID) values (13,to_date('12-OCT-22','DD-MON-RR'),6);
Insert into C##WSHOPR.PRODUCT_DATES (PRODUCT_ID,PRODUCT_DATE,LOCATION_ID) values (12,to_date('01-OCT-22','DD-MON-RR'),5);
Insert into C##WSHOPR.PRODUCT_DATES (PRODUCT_ID,PRODUCT_DATE,LOCATION_ID) values (12,to_date('02-OCT-22','DD-MON-RR'),4);
Insert into C##WSHOPR.PRODUCT_DATES (PRODUCT_ID,PRODUCT_DATE,LOCATION_ID) values (12,to_date('12-NOV-22','DD-MON-RR'),2);
Insert into C##WSHOPR.PRODUCT_DATES (PRODUCT_ID,PRODUCT_DATE,LOCATION_ID) values (12,to_date('11-NOV-22','DD-MON-RR'),3);
Insert into C##WSHOPR.PRODUCT_DATES (PRODUCT_ID,PRODUCT_DATE,LOCATION_ID) values (12,to_date('14-NOV-22','DD-MON-RR'),1);
