REM INSERTING into C##WSHOPR.PRODUCTS
SET DEFINE OFF;
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (2,'Cream Corn 125g','Cream corn 6x125g','ambient',8,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (3,' Rglr Corn 125g','regular corn 6x125g','ambient',8,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (4,'Spcy Corn 125g','spicey corn 6x125g','ambient',8,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (5,'Beans 100g','Bobs freerange Beans Plain 12x100g','ambient',8,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (6,'Beans 200g','Bobs freerange Beans Plain 6x200g','ambient',8,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (7,'Coc Mud 6x60g','Cakes n co, Choclete Mud Cake 6x60g','chill',9,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (8,'Caramel Mud 6x60g','Cakes n co, Caramel Mud Cake 6x60g','chill',9,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (9,'cookies Mud 6x60g','Cakes n co, Cookies And Cream Mud Cake 6x60g','chill',9,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (10,'Vanilla Ice 3x220g','Cakes n co, Vanilla Cake 3x220g','ambient',9,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (11,'Choclete Ice 3x220g','Cakes n co, Choclete Cake 3x220g','ambient',9,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (12,'Caramel Ice 3x220g','Cakes n co, Caramel Cake 3x220g','ambient',9,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (13,'Mint Ice 3x220g','Cakes n co, Mint Cake 3x220g','ambient',9,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (14,'Pies Meat','Mighty Meats, Meat pies 12x500Gg','frozen',10,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (15,'Pies Meat Veg','Mighty Meats, Meat Veggie pies 12x500Gg','frozen',10,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (16,'Pies Bacon','Mighty Meats, Bacon pies 12x500Gg','frozen',10,1);
Insert into C##WSHOPR.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC,PRODUCT_STORAGE_TYPE,SUPPLIER_ID,PRODUCT_IMG_ID) values (17,'Pies vegan','Mighty Meats, Vegan pies 12x500Gg','frozen',10,1);
