REM INSERTING into C##WSHOPR.SUPPLIERS
SET DEFINE OFF;
Insert into C##WSHOPR.SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME,SUPPLIER_ADDRESS,SUPPLIER_PHONE,SUPPLIER_EMAIL,COURIER_ID) values (8,'Bobs Freerange Beans','12 Apple st, Cannington, Perth, WA',422124321,'bobsfreerangebeanscorp@gmail.com',7);
Insert into C##WSHOPR.SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME,SUPPLIER_ADDRESS,SUPPLIER_PHONE,SUPPLIER_EMAIL,COURIER_ID) values (9,'Cakes N CO','23rd Ave, Midland, Perth, WA',4123454,'cakesnco@cakesncoadmin.com',7);
Insert into C##WSHOPR.SUPPLIERS (SUPPLIER_ID,SUPPLIER_NAME,SUPPLIER_ADDRESS,SUPPLIER_PHONE,SUPPLIER_EMAIL,COURIER_ID) values (10,'Mighty Meats','13 st, Swan view, Perth, WA',244123432,'jenny@mightymeats.com',11);
