--------------------------------------------------------
--  DDL for Table COURIERS
--------------------------------------------------------

  CREATE TABLE "C##WSHOPR"."COURIERS" 
   (	"COURIER_ID" NUMBER(10,0), 
	"COURIER_NAME" VARCHAR2(50 BYTE), 
	"COURIER_ADDRESS" VARCHAR2(50 BYTE), 
	"COURIER_PHONE" NUMBER(10,0), 
	"COURIER_EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "C##WSHOPR"."CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER(10,0), 
	"CUSTOMER_NAME" VARCHAR2(50 BYTE), 
	"CUSTOMER_ADDRESS" VARCHAR2(50 BYTE), 
	"CUSTOMER_PHONE" NUMBER(10,0), 
	"CUSTOMER_EMAIL" VARCHAR2(50 BYTE), 
	"COURIER_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "C##WSHOPR"."EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER(38,0), 
	"EMPLOYEE_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS" ;
--------------------------------------------------------
--  DDL for Table LOCATIONS_IN_WAREHOUSE
--------------------------------------------------------

  CREATE TABLE "C##WSHOPR"."LOCATIONS_IN_WAREHOUSE" 
   (	"LOCATION_ID" NUMBER(38,0), 
	"OCCUPIED" NUMBER(1,0), 
	"PRODUCT_STORAGE_TYPE" VARCHAR2(10 BYTE), 
	"LOCATION_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "C##WSHOPR"."ORDERS" 
   (	"ORDER_ID" NUMBER(38,0), 
	"CUSTOMER_ID" NUMBER(38,0), 
	"ORDER_DATE" DATE, 
	"ORDER_COMPLETED" NUMBER(1,0), 
	"ORDER_DATE_COMPLETED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS" ;
--------------------------------------------------------
--  DDL for Table ORDER_ITEMS
--------------------------------------------------------

  CREATE TABLE "C##WSHOPR"."ORDER_ITEMS" 
   (	"PRODUCT_ID" NUMBER(38,0), 
	"ORDER_ID" NUMBER(38,0), 
	"ORDER_QTY" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "C##WSHOPR"."PRODUCTS" 
   (	"PRODUCT_ID" NUMBER(38,0), 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"PRODUCT_DESC" VARCHAR2(100 BYTE), 
	"PRODUCT_STORAGE_TYPE" VARCHAR2(50 BYTE), 
	"SUPPLIER_ID" NUMBER(38,0), 
	"PRODUCT_IMG_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT_DATES
--------------------------------------------------------

  CREATE TABLE "C##WSHOPR"."PRODUCT_DATES" 
   (	"PRODUCT_ID" NUMBER(38,0), 
	"PRODUCT_DATE" DATE, 
	"LOCATION_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT_IMAGES
--------------------------------------------------------

  CREATE TABLE "C##WSHOPR"."PRODUCT_IMAGES" 
   (	"PRODUCT_IMG_ID" NUMBER(38,0), 
	"IMAGE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS" 
 LOB ("IMAGE") STORE AS SECUREFILE (
  TABLESPACE "TBS_PERM_WRHSEOPNS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PRODUCT_STORAGE
--------------------------------------------------------

  CREATE TABLE "C##WSHOPR"."PRODUCT_STORAGE" 
   (	"PRODUCT_ID" NUMBER(38,0), 
	"LOCATION_ID" NUMBER(38,0), 
	"PRODUCT_QTY" NUMBER(38,0), 
	"PRODUCT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS" ;
--------------------------------------------------------
--  DDL for Table SUPPLIERS
--------------------------------------------------------

  CREATE TABLE "C##WSHOPR"."SUPPLIERS" 
   (	"SUPPLIER_ID" NUMBER(38,0), 
	"SUPPLIER_NAME" VARCHAR2(100 BYTE), 
	"SUPPLIER_ADDRESS" VARCHAR2(100 BYTE), 
	"SUPPLIER_PHONE" NUMBER(38,0), 
	"SUPPLIER_EMAIL" VARCHAR2(100 BYTE), 
	"COURIER_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_WRHSEOPNS" ;
